### ISSUE TITLE
Collage page is not rendered well on Plone 4.3.6

### ISSUE THREAD

**Issue by takemura1958** [collective/Products.Collage#6]
I recently updated my site from Plone 4.3.3 to 4.3.6.
I found a collage page is displayed without any styles and other css settings.
The header of the a collage page becomes like the followings.

<!DOCTYPE html>
\<html xmlns="http://www.w3.org/1999/xhtml"> \<head> \<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> \<base href="http://www.my.site.com/8080/Plone/testclg/" />\</head>\<body>

**Comment by Martronic-SA** [comment]
Exactly the same issue here. It seems that the REQUEST is not tagged with ICMFDefaultSkin therefore the collage rendering template doesn't get the CMF's "@@standard_macros" but the default one from zope instead.
I don't know how to solve this issue.
Help needed please!
Thank you.

**Comment by Martronic-SA** [comment]
It seems that context is loosing something.
in collage_view.pt 
replace 
context/@@standard_macros/page
by
here/@@standard_macros/page

**Comment by vsanchez** [comment]
Hi, changing "context" for "here" did not work for me. However, when looking at the template at the portal_view_customizations there is an error message: 

Macro expansion failed
<type 'exceptions.AttributeError'>: widget

It happens with "here" or "context". Any suggestions?

**Comment by pigeonflight** [comment]
I have a similar problem of collage pages breaking after upgrade to Plone 4.3.6

**Comment by pigeonflight** [comment]
I've found a workaround.

Replace:

    <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en"
          lang="en"
          metal:use-macro="context/@@standard_macros/page"
          i18n:domain="collage">

with:

    <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en"
          lang="en"
          metal:use-macro="context/main_template/macros/master"
          i18n:domain="collage">

**Comment by pigeonflight** [comment]
Another solution to this issue is to pin plone.theme to 2.1.5. (Plone 4.3.6 ships with 2.1.4 which removes a dependency on CMFDefault, probably in preparation for Plone 5, but it has unintended consequences which plone.theme 2.1.5 fixes).

You'll want this placed somewhere in a versions file.

    [versions]
    ...
    plone.theme = 2.1.5

**Comment by jensens** [comment]
closed by #7
